
module.exports = {
 test_person: {
    media_type: 'person',
    results: [
        {
            popularity: 5.383765,
            id: 2636,
            profile_path: '/nA6zRjaVk1JjYvRpuihXJ2pirWk.jpg',
            name: 'Alfred Hitchcock',
            known_for: [Object],
            adult: false
        }
    ]
},
test_company: {
    media_type: 'company',
    results: [
        {
            id: 10715,
            logo_path: null,
            name: 'Alfred J. Hitchcock Productions'
        }
    ]
},
test_tv:  {
    media_type: 'tv',
    results: [
        {
            original_name: 'Alfred Hitchcock Presents',
            id: 5273,
            name: 'Alfred Hitchcock Presents',
            vote_count: 48,
            vote_average: 7.8,
            poster_path: '/8T26t54uCoh7Lej9foB1ENKnXxg.jpg',
            first_air_date: '1955-10-02',
            popularity: 14.63392,
            genre_ids: [Object],
            original_language: 'en',
            backdrop_path: '/zRacCjAo9v265NVhAV3wQjY8Y4F.jpg',
            overview: 'Alfred Hitchcock Presents is an American television anthology series hosted by Alfred Hitchcock. The series featured dramas, thrillers, and mysteries. By the time the show premiered on October 2, 1955, Hitchcock had been directing films for over three decades. Time magazine named Alfred Hitchcock Presents one of "The 100 Best TV Shows of All-TIME".\n\nA series of literary anthologies with the running title Alfred Hitchcock Presents were issued to capitalize on the success of the television series. One volume, devoted to stories that censors wouldn\'t allow to be adapted for the TV series, was entitled Alfred Hitchcock Presents: Stories They Wouldn\'t Let Me Do on TV—though eventually several of the stories collected were adapted.',
            origin_country: [Object]
        },
        {
            original_name: 'The Alfred Hitchcock Hour',
            id: 21728,
            name: 'The Alfred Hitchcock Hour',
            vote_count: 13,
            vote_average: 7.62,
            poster_path: '/mv8LvxX6Mh6zYbGaAbG60KUwkOT.jpg',
            first_air_date: '1962-09-20',
            popularity: 6.206711,
            genre_ids: [Object],
            original_language: 'en',
            backdrop_path: '/zRacCjAo9v265NVhAV3wQjY8Y4F.jpg',
            overview: 'A continuation of the dramatic anthology series "Alfred Hitchcock Presents" hosted by the master of suspense and mystery.',
            origin_country: []
        },
        {
            original_name: 'The New Alfred Hitchcock Presents',
            id: 2751,
            name: 'The New Alfred Hitchcock Presents',
            vote_count: 9,
            vote_average: 6.72,
            poster_path: '/iyI5tfqiLSFOkfUkjYKOhPBb7mT.jpg',
            first_air_date: '1985-09-29',
            popularity: 7.231938,
            genre_ids: [Object],
            original_language: 'en',
            backdrop_path: '/r4G1x4NfF4F7XYsEzyBvSzzugFZ.jpg',
            overview: 'The New Alfred Hitchcock Presents is an American anthology series that aired on NBC from 1985 to 1986, and on the USA Network from 1987 to 1989. The series is an updated re-imagining of the classic 1955 series Alfred Hitchcock Presents.',
            origin_country: [Object]
        },
        {
            original_name: 'Myster Mocky présente',
            id: 40001,
            name: 'Myster Mocky présente',
            vote_count: 0,
            vote_average: 0,
            poster_path: null,
            first_air_date: '',
            popularity: 1.25,
            genre_ids: [],
            original_language: 'en',
            backdrop_path: null,
            overview: '',
            origin_country: [Object]
        }
    ]
},
test_movie: {
    media_type: 'movie',
  results:
   [ { vote_count: 0,
       id: 323704,
       video: false,
       vote_average: 0,
       title: 'Alfred Hitchcock: Master of Suspense',
       popularity: 1.017667,
       poster_path: null,
       original_language: 'en',
       original_title: 'Alfred Hitchcock: Master of Suspense',
       genre_ids: [],
       backdrop_path: null,
       adult: false,
       overview: 'This is a wonderful and revealing film about famed horror and suspense director Alfred Hitchcock. You\'ll see behind-the-scenes of some of his most famous films including Psycho, Rear Window, Dial M for Murder, Vertigo and many more! Containing interviews, unique production shorts, trailers, film clips, news segments, and more, this collection offers a rare look into the life and times of this man who became a Hollywood legend and the undisputed Master of Suspense!',
       release_date: '2013-09-17' },
     { vote_count: 0,
       id: 306195,
       video: false,
       vote_average: 0,
       title: 'Alfred Hitchcock: More Than Just a Profile',
       popularity: 1.002374,
       poster_path: null,
       original_language: 'en',
       original_title: 'Alfred Hitchcock: More Than Just a Profile',
       genre_ids: [],
       backdrop_path: null,
       adult: false,
       overview: 'No one comes close to the undisputed master of the macabre and suspense as Alfred Hitchcock. The rotund figure of the smiling, unassuming Englishman is as recognizable as his work, thanks in part to his wonderful cameo appearances and to having crafted such classics like "Psycho," "The Birds," "Rear Window," and "Dial M For Murder". Hitchcock is a name that no one will soon forget. There is, however, another incredible story to be told here--that of the great director Alfred Hitchcock himself, who was born to London shopkeepers in the unassuming suburb of Leytonstone. A self-made man, Hitchcock was determined to break into the British Film Industry, and of course, he succeeded. Then when America and Hollywood beckoned, he rose to the challenge once again, and the rest is movie history.',
       release_date: '2005-06-07' },
     { vote_count: 0,
       id: 155988,
       video: false,
       vote_average: 0,
       title: 'The Men Who Made the Movies: Alfred Hitchcock',
       popularity: 1.317823,
       poster_path: '/3nvWrRSm3d6DTCcqBDH5F5ZauV0.jpg',
       original_language: 'en',
       original_title: 'The Men Who Made the Movies: Alfred Hitchcock',
       genre_ids: [],
       backdrop_path: null,
       adult: false,
       overview: 'A look at Alfred Hitchcock\'s films. The Master of Suspense himself, who is interviewed extensively here, shares stories including his deep-seated fear of policemen, elaborates on the difference between shock and suspense, defines the meaning of "MacGuffin," and discusses his use of storyboarding in designing a film. Clips from many of his greatest films (including "North by Northwest", "Shadow of a Doubt", "The Birds", and the legendary shower scene from "Psycho") illustrate his points, often to Hitchcock\'s own voice-over observations, with narrator Cliff Robertson offering other critical insights.',
       release_date: '1973-01-01' },
     { vote_count: 0,
       id: 339418,
       video: false,
       vote_average: 0,
       title: 'Alfred Hitchcock\'s Lifeboat: The Theater of War',
       popularity: 1.00462,
       poster_path: null,
       original_language: 'en',
       original_title: 'Alfred Hitchcock\'s Lifeboat: The Theater of War',
       genre_ids: [Object],
       backdrop_path: null,
       adult: false,
       overview: '\'Making of\' featurette about director Alfred Hitchcock masterpiece classic Lifeboat (1944). Narrated by the director\'s daughter and granddaughter, a Hitchcock scholar and a John Steinbeck specialist.',
       release_date: '2005-10-18' },
     { vote_count: 0,
       id: 445601,
       video: false,
       vote_average: 0,
       title: 'Shipwrecked in a Studio: The Making of Alfred Hitchcock\'s Jamaica Inn',
       popularity: 1.022695,
       poster_path: '/7jaSd1gktB7aYXBBzEFJC5OPtAo.jpg',
       original_language: 'en',
       original_title: 'Shipwrecked in a Studio: The Making of Alfred Hitchcock\'s Jamaica Inn',
       genre_ids: [Object],
       backdrop_path: null,
       adult: false,
       overview: 'A short documentary featuring Donald Spoto about the making of Alfred Hitchcock\'s \'Jamaica Inn\'.',
       release_date: '2015-05-12' },
     { vote_count: 927,
       id: 571,
       video: false,
       vote_average: 7.3,
       title: 'The Birds',
       popularity: 42.638542,
       poster_path: '/z0iYrJ6GsAMP3abOha7uGMuc5kZ.jpg',
       original_language: 'en',
       original_title: 'The Birds',
       genre_ids: [Object],
       backdrop_path: '/oHrTL0iTwLJMKbx2T3R5L5DPSyz.jpg',
       adult: false,
       overview: 'Chic socialite Melanie Daniels enjoys a passing flirtation with an eligible attorney in a San Francisco pet shop and, on an impulse, follows him to his hometown bearing a gift of lovebirds. But upon her arrival, the bird population runs amok. Suddenly, the townsfolk face a massive avian onslaught, with the feathered fiends inexplicably attacking people all over Bodega Bay.',
       release_date: '1963-03-28' },
     { vote_count: 521,
       id: 1580,
       video: false,
       vote_average: 7.8,
       title: 'Rope',
       popularity: 27.734132,
       poster_path: '/8JUyhb3j4d4KMPizrPUyDcYfovY.jpg',
       original_language: 'en',
       original_title: 'Rope',
       genre_ids: [Object],
       backdrop_path: '/2RWBzG3DYGYmgbsazg3Fls0X02l.jpg',
       adult: false,
       overview: 'Two young men strangle their "inferior" classmate, hide his body in their apartment, and invite his friends and family to a dinner party as a means to challenge the "perfection" of their crime.',
       release_date: '1948-08-23' },
     { vote_count: 59,
       id: 1978,
       video: false,
       vote_average: 6.8,
       title: 'Stage Fright',
       popularity: 5.074695,
       poster_path: '/1W7RzrENooOXQVeYMlF8Vx3EpAk.jpg',
       original_language: 'en',
       original_title: 'Stage Fright',
       genre_ids: [Object],
       backdrop_path: '/97G8umelca6lGI0ZqhlkqUIV21F.jpg',
       adult: false,
       overview: 'A struggling actress tries to help a friend prove his innocence when he\'s accused of murdering the husband of a high society entertainer.',
       release_date: '1950-02-23' },
     { vote_count: 1117,
       id: 426,
       video: false,
       vote_average: 8,
       title: 'Vertigo',
       popularity: 48.732743,
       poster_path: '/obhM86qyv8RsE69XSMTtT9FdE0b.jpg',
       original_language: 'en',
       original_title: 'Vertigo',
       genre_ids: [Object],
       backdrop_path: '/idbDJjoTQxLejUUkDJ0FNEim6FB.jpg',
       adult: false,
       overview: 'A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend\'s wife, all the while becoming dangerously obsessed with her.',
       release_date: '1958-05-09' },
     { vote_count: 514,
       id: 112336,
       video: false,
       vote_average: 6.3,
       title: 'Hitchcock',
       popularity: 20.996478,
       poster_path: '/qQGr8DQiAelkcy4w8cXn2qTMkMq.jpg',
       original_language: 'en',
       original_title: 'Hitchcock',
       genre_ids: [Object],
       backdrop_path: '/wLczRlndrKOFcBffSzUEKNyBEi2.jpg',
       adult: false,
       overview: 'Hitchcock follows the relationship between director Alfred Hitchcock and his wife Alma Reville during the making of his most famous film "Psycho" - and the trials and tribulations the director faced from Hollywood censors.',
       release_date: '2012-11-22' },
     { vote_count: 1490,
       id: 567,
       video: false,
       vote_average: 8.1,
       title: 'Rear Window',
       popularity: 64.078824,
       poster_path: '/oXbT7vlLmZ76kWoHe5XJYuyJUgp.jpg',
       original_language: 'en',
       original_title: 'Rear Window',
       genre_ids: [Object],
       backdrop_path: '/s9Up9JCwmIY13XoIo3ZJ1mtMLVc.jpg',
       adult: false,
       overview: 'Professional photographer L.B. "Jeff" Jeffries breaks his leg while getting an action shot at an auto race. Confined to his New York apartment, he spends his time looking out of the rear window observing the neighbors. He begins to suspect that a man across the courtyard may have murdered his wife. Jeff enlists the help of his high society fashion-consultant girlfriend Lisa Freemont and his visiting nurse Stella to investigate.',
       release_date: '1954-08-01' },
     { vote_count: 89,
       id: 31997,
       video: false,
       vote_average: 6.8,
       title: 'Saboteur',
       popularity: 5.195802,
       poster_path: '/x5l97t0FqYKisYNcEbwHWPvnBUH.jpg',
       original_language: 'en',
       original_title: 'Saboteur',
       genre_ids: [Object],
       backdrop_path: '/lZchBGbbXhBKrr11fPzGxJFxXUj.jpg',
       adult: false,
       overview: 'Aircraft factory worker Barry Kane goes on the run across the United States when he is wrongly accused of starting a fire that killed his best friend.',
       release_date: '1942-04-24' },
     { vote_count: 16,
       id: 36049,
       video: false,
       vote_average: 5.5,
       title: 'Rich and Strange',
       popularity: 3.334142,
       poster_path: '/eDMrDdi85s2kHU1tBR5jS5lStkb.jpg',
       original_language: 'en',
       original_title: 'Rich and Strange',
       genre_ids: [Object],
       backdrop_path: '/l5z8WRtoGesGrI8HObV7WmzNB20.jpg',
       adult: false,
       overview: 'A couple, Fred (Henry Kendall) and Emily Hill (Joan Barry) , living a mundane middle-class life in London, are given a small fortune by an uncle as an advance against their future inheritance so that they can enjoy it in the present. Immediately Fred takes leave from his job as a clerk and they leave on a cruise for "the Orient". Fred quickly shows his susceptibility to sea-sickness while crossing',
       release_date: '1931-12-10' },
     { vote_count: 43,
       id: 31995,
       video: false,
       vote_average: 5.6,
       title: 'Jamaica Inn',
       popularity: 3.852495,
       poster_path: '/80V3ScsMRzsuLF0T17SlRN4tiah.jpg',
       original_language: 'en',
       original_title: 'Jamaica Inn',
       genre_ids: [Object],
       backdrop_path: '/55W7YNtxgbVlRrRoerQQc2EUT3C.jpg',
       adult: false,
       overview: 'In coastal Cornwall, England, during the early 19th Century, a young woman discovers that she\'s living with a gang of criminals who arrange shipwrecking for profit.',
       release_date: '1939-05-11'
    }
   ]
   }
}
